--liquibase formatted sql
--changeset lianyitech:4

CREATE TABLE CATALOG_SUPPLY_LABLE
(
  ID VARCHAR2(64) PRIMARY KEY NOT NULL,
  ORG_ID VARCHAR2(64),
  TYPE CHAR(1),
  BAR_CODE VARCHAR2(64),
  LIBRARSORT_CODE VARCHAR2(64),
  TANEJI_NO VARCHAR2(64),
  ASS_NO VARCHAR2(64),
  BOOK_NO VARCHAR2(64),
  BOOK_TIME_NO VARCHAR2(64),
  TITLE_NAME VARCHAR2(64),
  PUT_DATE TIMESTAMP(6),
  CREATE_BY VARCHAR2(64),
  CREATE_DATE TIMESTAMP(6),
  UPDATE_BY VARCHAR2(64),
  UPDATE_DATE TIMESTAMP(6),
  REMARKS NVARCHAR2(255),
  DEL_FLAG CHAR(1)
);
COMMENT ON COLUMN CATALOG_SUPPLY_LABLE.ID IS '主键id';
COMMENT ON COLUMN CATALOG_SUPPLY_LABLE.ORG_ID IS '机构id';
COMMENT ON COLUMN CATALOG_SUPPLY_LABLE.TYPE IS '类型 0书目 1期刊';
COMMENT ON COLUMN CATALOG_SUPPLY_LABLE.BAR_CODE IS '条形码';
COMMENT ON COLUMN CATALOG_SUPPLY_LABLE.LIBRARSORT_CODE IS '中图分类号';
COMMENT ON COLUMN CATALOG_SUPPLY_LABLE.TANEJI_NO IS '种次号';
COMMENT ON COLUMN CATALOG_SUPPLY_LABLE.ASS_NO IS '辅助区分号';
COMMENT ON COLUMN CATALOG_SUPPLY_LABLE.BOOK_NO IS '著者号';
COMMENT ON COLUMN CATALOG_SUPPLY_LABLE.BOOK_TIME_NO IS '书次号';
COMMENT ON COLUMN CATALOG_SUPPLY_LABLE.TITLE_NAME IS '题名/刊名';
COMMENT ON COLUMN CATALOG_SUPPLY_LABLE.PUT_DATE IS '入库日期';
COMMENT ON COLUMN CATALOG_SUPPLY_LABLE.CREATE_BY IS '创建人';
COMMENT ON COLUMN CATALOG_SUPPLY_LABLE.CREATE_DATE IS '创建时间';
COMMENT ON COLUMN CATALOG_SUPPLY_LABLE.UPDATE_BY IS '更新人';
COMMENT ON COLUMN CATALOG_SUPPLY_LABLE.UPDATE_DATE IS '更新时间';
COMMENT ON COLUMN CATALOG_SUPPLY_LABLE.REMARKS IS '备注';
COMMENT ON COLUMN CATALOG_SUPPLY_LABLE.DEL_FLAG IS '删除标示 0未删除 1已删除';


--rollback DROP TABLE CATALOG_SUPPLY_LABLE;
